FROM alpine:3.12

RUN apk add --no-cache msgpack-c ncurses-libs libevent libexecinfo openssl zlib

RUN set -ex; \
	apk add --no-cache --virtual .build-deps \
		libssh-dev \
		git wget cmake make gcc g++ linux-headers zlib-dev openssl-dev \
		automake autoconf libevent-dev ncurses-dev msgpack-c-dev libexecinfo-dev; \

WORKDIR /src/tmate-ssh-server

COPY . .

RUN set -ex; \
	./autogen.sh; \
	./configure --prefix=/usr CFLAGS="-D_GNU_SOURCE"; \
	make -j "$(nproc)"; \
  ln -s /src/tmate-ssh-server/tmate-ssh-server /usr/bin

COPY docker-entrypoint.sh /usr/local/bin

ENTRYPOINT ["docker-entrypoint.sh"]
